
cc_library(
    name = "libtestsanity",
    srcs = ["test_sanity.c"],
    deps = [
        "//cmocka:cmocka",
        ],
)

cc_test(
    name = "sanity",
    deps = [
        ":libtestsanity",
    ],
)


