

cc_library(
    name = "wheel_hdr",
    hdrs = ["wheel.h"],
    deps = [],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "echo_hdr",
    hdrs = ["echo.h"],
    deps = [
       "//robot/logic:robottypes_hdr", 
        ],
    visibility = ["//visibility:public"],
)


