cc_library(
    name = "switch_hdr",
    hdrs = ["switch.h"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "switch_h_fg",
    srcs = [
        "switch.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "echo_hdr",
    hdrs = ["echo.h"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "echo_h_fg",
    srcs = [
        "echo.h",
    ],
    visibility = ["//visibility:public"],
)
cc_library(
    name = "lcd_hdr",
    hdrs = ["lcd.h"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "lcd_h_fg",
    srcs = [
        "lcd.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "shoot_hdr",
    hdrs = ["shoot.h"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "shoot_h_fg",
    srcs = [
        "shoot.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "wheel_hdr",
    hdrs = ["wheel.h"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "wheel_h_fg",
    srcs = [
        "wheel.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "robotime_hdr",
    hdrs = ["robotime.h"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "robotime_h_fg",
    srcs = [
        "robotime.h",
    ],
    visibility = ["//visibility:public"],
)
